#!/usr/bin/env python3
import requests
import gzip
import re
import datetime

BASE = "https://tgftp.nws.noaa.gov/data/observations/metar/cycles/"
ICAO_RE = re.compile(r"^[A-Z]{4}", re.MULTILINE)

# CONFIG: minimum number of cycles an airport must appear in (1–24)
FILTER_COUNT = 12   # 1 = current behavior, higher = more stable lists

def fetch_cycle(hour):
    url = f"{BASE}{hour:02d}Z.TXT"
    print(f"Fetching {url} ...")
    try:
        return requests.get(url, timeout=10).text
    except Exception as e:
        print(f"Failed to fetch {url}: {e}")
        return ""

def extract_icaos(text):
    return ICAO_RE.findall(text)

def main():
    # Count ICAO occurrences across all 24 cycles
    counts = {}

    for hour in range(24):
        text = fetch_cycle(hour)
        icaos = extract_icaos(text)
        for icao in icaos:
            counts[icao] = counts.get(icao, 0) + 1

    # Apply FILTER_COUNT threshold
    filtered_icaos = sorted([icao for icao, n in counts.items() if n >= FILTER_COUNT])

    # Header WITHOUT date (stable diff)
    header = (
        "# List of airports known to have METAR data available\n"
        "# Generated by generate_metar_dat.py\n"
        "# Source: NOAA TGFTP METAR cycles\n"
        "# https://tgftp.nws.noaa.gov/data/observations/metar/cycles/\n"
    )

    # Write metar.dat
    with open("metar.dat", "w") as f:
        f.write(header)
        for icao in filtered_icaos:
            f.write(icao + "\n")

    # Compress to metar.dat.gz
    with gzip.open("metar.dat.gz", "wb") as gz:
        gz.write(open("metar.dat", "rb").read())

    print(f"Generated metar.dat.gz with {len(filtered_icaos)} airports "
          f"(FILTER_COUNT = {FILTER_COUNT}).")

if __name__ == "__main__":
    main()
