#!/usr/bin/env python3
import requests
import gzip
import re
import datetime

BASE = "https://tgftp.nws.noaa.gov/data/observations/metar/cycles/"
ICAO_RE = re.compile(r"^[A-Z]{4}", re.MULTILINE)

def fetch_cycle(hour):
    url = f"{BASE}{hour:02d}Z.TXT"
    print(f"Fetching {url} ...")
    try:
        return requests.get(url, timeout=10).text
    except Exception as e:
        print(f"Failed to fetch {url}: {e}")
        return ""

def extract_icaos(text):
    return ICAO_RE.findall(text)

def main():
    all_icaos = set()

    # Fetch all 24 cycle files
    for hour in range(24):
        text = fetch_cycle(hour)
        icaos = extract_icaos(text)
        all_icaos.update(icaos)

    # Sort ICAOs alphabetically
    sorted_icaos = sorted(all_icaos)

    # Build descriptive header
    today = datetime.datetime.utcnow().strftime("%Y-%m-%d")
    header = (
        "# List of airports known to have METAR data available\n"
        f"# Generated by generate_metar_dat.py on {today}\n"
        "# Source: NOAA TGFTP METAR cycles\n"
        "# https://tgftp.nws.noaa.gov/data/observations/metar/cycles/\n"
    )

    # Write metar.dat (NO blank line before list)
    with open("metar.dat", "w") as f:
        f.write(header)
        for icao in sorted_icaos:
            f.write(icao + "\n")

    # Compress to metar.dat.gz
    with gzip.open("metar.dat.gz", "wb") as gz:
        gz.write(open("metar.dat", "rb").read())

    print(f"Generated metar.dat.gz with {len(sorted_icaos)} airports.")

if __name__ == "__main__":
    main()
